### ISSUE TITLE
addEventListener issue in Edge and iosSafari

### ISSUE THREAD

**Issue by Gagydzer** [scaccogatto/vue-viewports#5]
i've got an error: "object doesn't support property or method addeventlistener" in Microsoft Edge and (probably) in iphone-safari (because my app start wokring after delete vue-viewports. I tried to use polyfill for addeventlistener, but of cours It didn't help (coz this method is supported in these browsers). 
¯ \ _ (ツ) _ / ¯

**Comment by scaccogatto** [comment]
Please check if the library is now working for you. Then we can close the issue.

**Comment by Gagydzer** [comment]
it's fixed, gj, thx.
